apiVersion: apps/v1
kind: Deployment
metadata:
  name: devweb-deployment
spec:
  selector:
    matchLabels:
      app: my-devweb
  replicas: 3
  template:
    metadata:
      labels:
        app: my-devweb
    spec:
      containers:
      - name: devweb-containers
        image: cho010515/myweb:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devweb-svc
spec:
  selector: 
    app: my-devweb
  ports:
  - port: 8090
    targetPort: 80
    nodePort: 10001 
  type: NodePort
